# Generated by Django 3.2.8 on 2022-05-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('ats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olt', to='back.ats')),
            ],
        ),
        migrations.CreateModel(
            name='ONT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('pon_id', models.IntegerField()),
                ('personal', models.CharField(max_length=100, null=True)),
                ('physic_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ont', to='back.olt')),
            ],
        ),
        migrations.CreateModel(
            name='RSSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rx', models.FloatField()),
                ('tx', models.FloatField()),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rssi', to='back.ont')),
            ],
        ),
        migrations.CreateModel(
            name='OPERATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('ch_user', models.BooleanField(null=True)),
                ('ch_login', models.BooleanField(null=True)),
                ('ch_password', models.BooleanField(null=True)),
                ('ch_profile', models.BooleanField(null=True)),
                ('ch_reconf', models.BooleanField(null=True)),
                ('ch_saved', models.BooleanField(null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ont', to='back.ont')),
            ],
        ),
    ]
