# Generated by Django 3.2.9 on 2022-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
