# Generated by Django 3.2.9 on 2022-07-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_olt_firmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_port', models.IntegerField()),
                ('to_port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('directionText', models.CharField(default='north', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.node')),
            ],
        ),
        migrations.CreateModel(
            name='Node_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edges', models.ManyToManyField(to='back.Edge')),
                ('nodes', models.ManyToManyField(to='back.Node')),
                ('positions', models.ManyToManyField(to='back.Position')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on', to='back.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='back.node'),
        ),
    ]
